MyNotes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MyNotes.Models;

namespace MyNotes.Controllers
{
    public class HomeController : Controller
    {

        private readonly ApplicationDbContext _db = new ApplicationDbContext();


        public ActionResult Index()
        {
            //var notes = from m in _db.Notes
            //            where m.Priority == Priority.High && m.Completed != true
            //            select m;

            var user = User.Identity.GetUserId();

            var notes = from m in _db.Notes
                where m.Priority == Priority.High && m.Completed != true && m.UserId==user
                select m;
            //return Content(notes.ToList().ToString());
            return View(notes.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MyNotes/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using MyNotes.Models;

namespace MyNotes.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {
        //private MyContext db = new MyContext();

        private ApplicationDbContext db = new ApplicationDbContext();
        

        // GET: Notes
        public ActionResult Index(Priority? priority)
        {
            var user = User.Identity.GetUserId();

            if (priority != null)
            {
                try
                {
                    var notes = from m in db.Notes
                        where m.Priority == priority && m.UserId == user
                                select m;
                    return View(notes.ToList());
                }
                catch (Exception)
                {

                    return Content("Błąd z pobraniem danych");

                }
            }
            else
            {
                var notes = from m in db.Notes
                    where m.UserId == user
                    select m;
                return View(notes.ToList());
            }

        }





        // GET: Notes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }



        public ActionResult Create()
        {
            return View();
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Note note)
        {
            if (ModelState.IsValid)
            {
                note.UserId = User.Identity.GetUserId();
                db.Notes.Add(note);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(note);
        }

        // GET: Notes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Note note)
        {
            if (ModelState.IsValid)
            {
                db.Entry(note).State = EntityState.Modified;
                db.Entry(note).Property(x => x.UserId).IsModified = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(note);
        }

        // GET: Notes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Note note = db.Notes.Find(id);
            db.Notes.Remove(note);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyNotes/Views/Home/About.cshtml
@{
    ViewBag.Title = "O tej stronie";
}
<h2>2016 Projekt na .NET </h2>
<h3>Krótki opis</h3>

<p>Aplikacja robiona na zaliczenie projektu z .Net.</p>
<p>Póki co znajdują się w niej tylko podstawowe funkcjonalności, jednak aplikacja będzie rozwijana - bo mi się kiedyś przyda</p>

MyNotes/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>Kontakt</h2>
<h3>To jest kontakt</h3>
<p><img src="http://www.kkskrakersy.pl/images/kontakt.jpg" alt="Kontakt"></p>



<address>
    <strong>I mój mail:</strong> <a href="mailto:mail.robert.malz@gmail.com">mail.robert.malz@gmail.com</a>
</address>

MyNotes/Views/Home/Index.cshtml
@model IEnumerable<MyNotes.Models.Note>
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Turbo Aplikacja</h1>
    <p class="lead">To jest miejsce, w którym kiedyś zrobię fajną grafikę</p>
    <p>W aplikacji zostały wykorzystane wszystkie wymagane w notatniku punkty. Cześć w formie frameworku część ręcznie.</p>
    <p>Jednak jeżeli czegoś by brakowało dajcie info, mail w kontakcie</p>
</div>

<div class="row">
    @{
        if (User.Identity.IsAuthenticated)
        {
            if (Model.Any())
            {
                <div class="col-md-4">
                    <h2>Pierwszy Feature</h2>
                    <p>
                        Uwaga masz aktualne notatki z wysokim priorytetem.
                    </p>
                    <p>
                        <a class="btn btn-default" href="@Url.Action("Index", "Notes")">Wyświetl je &raquo;</a>
                    </p>
                </div>
            }
            else
            {

                <div class="col-md-4">
                    <h2>Pierwszy Feature</h2>
                    <p>
                        Nie masz żadnych notatek z wysokim priorytetem.
                    </p>
                    <p>
                        <a class="btn btn-default" href="@Url.Action("Index", "Notes")">Pokaż notatki &raquo;</a>
                    </p>
                </div>
            }
        }
        else
        {
            <div class="col-md-4">
                <h2>Pierwszy Feature</h2>
                <p>
                    Nie jesteś zalogowany. </p>
                <p>
                    <a class="btn btn-default" href="@Url.Action("Login", "Account")">Zaloguj się &raquo;</a>
                </p>
            </div>

        }


    }
    <div class="col-md-4">
        <h2>TODO1</h2>
        <p>Some stuff todo</p>
        <p><a class="btn btn-default" href="#">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>TODO2</h2>
        <p>More stuff todo</p>
        <p><a class="btn btn-default" href="#">Learn more &raquo;</a></p>
    </div>
</div>